### ISSUE TITLE
Request for mentors at LNUG

### ISSUE THREAD

**Issue by iteles** [node-girls/start-here#5]
Speak to @iancrowther and ask if we can put out a request for female mentors for Node Girls (February) at the January LNUG.

**Comment by iancrowther** [comment]
are you coming for LNUG drinks tomorrow? you ask in person then :-)

and yes, of course you can ask.. want it in the newsletter?

**Comment by iteles** [comment]
@iancrowther You make my life so easy 😄
Sadly I can't come tomorrow because I'll be on my way out of town for family festivities, but I'll drop you an email over the weekend on this 😊 (And yes, we'd love it in the newsletter!)

**Comment by iancrowther** [comment]
ok add the details here - https://github.com/lnug/feedback/issues/76

**Comment by iancrowther** [comment]
merry christmas btw..

**Comment by iteles** [comment]
@iancrowther Do we need to do anything to get on the schedule for the announcements at the end?

**Comment by iancrowther** [comment]
Be there.. The rest will work like magic

**Comment by iteles** [comment]
@iancrowther Amazing! @nataliaLKB and I will do just that :)

**Comment by NataliaLKB** [comment]
@iancrowther Thank you! :star:

**Comment by iteles** [comment]
Done! Thanks @NataliaLKB @nikhilaravi

**Comment by iancrowther** [comment]
dont forget to add details to https://github.com/lnug/feedback/issues/96

**Comment by iteles** [comment]
@iancrowther Done! Thanks :ok_woman:
